[package]
name = "openpart-cli"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/mahmadabid/OpenPart"

[[bin]]
name = "openpart-cli"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
openpart-core = { path = "../openpart-core" }
openpart-service = { path = "../openpart-service" }

[build-dependencies]
tauri-winres = "0.1"
